#!/bin/bash

pushd src/my_db
rm -rf node_modules
popd

pushd src/my_util
npm install
popd

pushd src/create_customer
rm -rf node_modules
npm install
rm -f ../../deploy/create_customer.zip
zip -q -r ../../deploy/create_customer.zip  .
popd

pushd src/create_job
rm -rf node_modules
npm install
rm -f ../../deploy/create_job.zip
zip -q -r ../../deploy/create_job.zip  .
popd

pushd src/get_job
rm -rf node_modules
npm install
rm -f ../../deploy/get_job.zip
zip -q -r ../../deploy/get_job.zip  .
popd

pushd src/create_task
rm -rf node_modules
npm install
rm -f ../../deploy/create_task.zip
zip -q -r ../../deploy/create_task.zip  .
popd

pushd src/create_user
rm -rf node_modules
npm install
rm -f ../../deploy/create_user.zip
zip -q -r ../../deploy/create_user.zip  .
popd

pushd deploy
ls -l *.zip
popd