#!/bin/bash

pushd src/my_db
rm -rf node_modules
popd

pushd src/my_util
npm install
popd

pushd src/create_job
rm -rf node_modules
npm install
rm -f ../../deploy/create_job.zip
zip -r ../../deploy/create_job.zip  .
popd

pushd src/get_job
rm -rf node_modules
npm install
rm -f ../../deploy/get_job.zip
zip -r ../../deploy/get_job.zip  .
popd